version: '1.0'
services:
  digital-solution-backend:
    build: ./digital-solution
    ports:
      - "8082:8082"
    env_file:
      - ./env/docker.env
    volumes:
      - ./data:/usr/src/app/data:rw
      

    